In [137]:
#Import all relevant libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import dtale as dt
from ydata_profiling import ProfileReport as pr
import sweetviz as sv
import plotly.express as px 
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
## This statement allows the visuals to render within your Jupyter Notebook.
%matplotlib inline

## Business

In [139]:
zahr_b = pd.read_csv('final_business_zahrah.csv')
swedi_b = pd.read_csv('final_business_swedi.csv')
yas_b = pd.read_csv('final_business_yasmin.csv')
falah_b = pd.read_csv('final_business_falah.csv')
aziz_b = pd.read_csv('final_business_azizya.csv')
mansour_b = pd.read_csv('final_business_mansora.csv')
roda_b = pd.read_csv('final_business_Rawdah.csv')
monsia_b = pd.read_csv('final_business_Munsiyah.csv')

## Age

In [141]:
zahr_a = pd.read_csv('final_age_zahrah.csv')
swedi_a = pd.read_csv('final_age_swedi.csv')
yas_a = pd.read_csv('final_age_yasmin.csv')
falah_a = pd.read_csv('final_age_falah.csv')
aziz_a = pd.read_csv('final_age_azizya.csv')
mansour_a = pd.read_csv('final_age_mansora.csv')
roda_a = pd.read_csv('final_age_Rawdah.csv')
monsia_a = pd.read_csv('final_age_Munsiyah.csv')

In [142]:
yas_pray = 44016  
falah_pray = 16295 
aziz_pray = 77024 
mansour_pray = 27247   
roda_pray = 40609  
monsia_pray = 34783  
swedi_pray = 67337 
zahr_pray = 43827

In [143]:
columns = [
    "Neighborhood", "Elementary schools","Secondary schools", "Gym", "Total population of the neighborhood", 'Population Density', 
    "Hospitals", "Parks", "Restaurants", "Cafes", "Mosques", 
    "Bus stations", "Metro stations", "Supermarkets",'Children_Ratio', 'Youth_Ratio', 'Adults_Ratio', 'Seniors_Ratio',
    'Children', 'Youth', 'Males above 10 years'  
]


df = pd.DataFrame(columns=columns)

In [144]:
fala = { 'Neighborhood': 'حي الفلاح', 'Elementary schools': 4, "Secondary schools": 8, 'Gym': 2,
         'Total population of the neighborhood' : 38710, 'Population Density': 9701.75, 'Hospitals': 3, 'Parks' : 2, 'Restaurants': 34, 
        'Cafes':12, 'Mosques': 21,	'Bus stations': 3, 'Metro stations':2,	'Supermarkets': 1,'Children_Ratio': 14.97, 'Youth_Ratio': 22.90, 
        'Adults_Ratio': 50.53, 'Seniors_Ratio': 11.58, 'Children': 5797, 'Youth': 8868, 'Males above 10 years': 16295 }

In [145]:
df = pd.concat([df, pd.DataFrame([fala])], ignore_index=True)

In [146]:
yasm = { 'Neighborhood': 'حي الياسمين', 'Elementary schools': 5, "Secondary schools": 9, 'Gym': 5,
         'Total population of the neighborhood' : 103116, 'Population Density': 8106.60, 'Hospitals': 5, 'Parks' : 6, 'Restaurants': 80, 
        'Cafes':40, 'Mosques': 60,	'Bus stations': 10, 'Metro stations':1,	'Supermarkets': 7,'Children_Ratio': 16.44, 'Youth_Ratio': 20.89, 
        'Adults_Ratio':53.09 , 'Seniors_Ratio': 9.57, 'Children': 16955, 'Youth': 21542, 'Males above 10 years': 44016 }

In [147]:
df = pd.concat([df, pd.DataFrame([yasm])], ignore_index=True)

In [148]:
azizi = { 'Neighborhood': 'حي العزيزية', 'Elementary schools': 31, "Secondary schools": 26, 'Gym': 7,
         'Total population of the neighborhood' : 174869, 'Population Density': 8403.12, 'Hospitals': 6, 'Parks' : 7, 'Restaurants': 162, 
        'Cafes':91, 'Mosques': 106,	'Bus stations': 48, 'Metro stations':2,	'Supermarkets': 5,'Children_Ratio': 18.33, 'Youth_Ratio': 23.75, 
        'Adults_Ratio': 46.36, 'Seniors_Ratio': 11.55, 'Children': 32055, 'Youth': 41540, 'Males above 10 years': 77024 }

In [149]:
df = pd.concat([df, pd.DataFrame([azizi])], ignore_index=True)

In [150]:
mansora = { 'Neighborhood': 'حي المنصورة', 'Elementary schools': 15, "Secondary schools": 11, 'Gym': 3,
         'Total population of the neighborhood' : 59401, 'Population Density':10085.05, 'Hospitals': 6, 'Parks' : 4, 'Restaurants': 100, 
        'Cafes':29, 'Mosques': 50,	'Bus stations': 13, 'Metro stations':3,	'Supermarkets': 17, 'Children_Ratio': 14.79, 'Youth_Ratio': 24.86, 
        'Adults_Ratio': 48.24, 'Seniors_Ratio': 12.08, 'Children': 8789, 'Youth': 14773, 'Males above 10 years': 27247  }

In [151]:
df = pd.concat([df, pd.DataFrame([mansora])], ignore_index=True)

In [152]:
munsia = { 'Neighborhood': 'حي المونسية', 'Elementary schools': 5, "Secondary schools": 8, 'Gym': 11,
         'Total population of the neighborhood' : 86315, 'Population Density': 5623.12, 'Hospitals': 3, 'Parks' : 4, 'Restaurants': 121, 
        'Cafes':46, 'Mosques': 50,	'Bus stations': 11, 'Metro stations':0,	'Supermarkets': 5, 'Children_Ratio': 20.41, 'Youth_Ratio': 19.19, 
        'Adults_Ratio': 53.71, 'Seniors_Ratio': 6.67, 'Children': 17625, 'Youth': 16565, 'Males above 10 years': 34783 }

In [153]:
df = pd.concat([df, pd.DataFrame([munsia])], ignore_index=True)

In [154]:
rawd = { 'Neighborhood': 'حي الروضة', 'Elementary schools': 20, "Secondary schools": 27, 'Gym': 11,
         'Total population of the neighborhood' : 92956, 'Population Density': 10672.33, 'Hospitals': 7, 'Parks' : 19, 'Restaurants': 140, 
        'Cafes':36, 'Mosques': 51,	'Bus stations': 11, 'Metro stations':1,	'Supermarkets': 11,'Children_Ratio': 17.08, 'Youth_Ratio': 18.38, 
        'Adults_Ratio': 51.94, 'Seniors_Ratio': 12.58, 'Children': 15883, 'Youth': 17090, 'Males above 10 years': 40609  }

In [155]:
df = pd.concat([df, pd.DataFrame([rawd])], ignore_index=True)

In [156]:
swd = { 'Neighborhood': 'حي السويدي', 'Elementary schools': 19, "Secondary schools": 19, 'Gym': 11,
         'Total population of the neighborhood' : 115457, 'Population Density': 20992.18, 'Hospitals': 8, 'Parks' : 8, 'Restaurants': 93, 
        'Cafes':60, 'Mosques': 53,	'Bus stations': 24, 'Metro stations':2,	'Supermarkets': 5, 'Children_Ratio': 11.23, 'Youth_Ratio': 16.58, 
        'Adults_Ratio': 60.76, 'Seniors_Ratio': 11.42, 'Children': 12970, 'Youth': 19146, 'Males above 10 years': 67337  }

In [157]:
df = pd.concat([df, pd.DataFrame([swd])], ignore_index=True)

In [158]:
zah = { 'Neighborhood': 'حي الزهرة', 'Elementary schools': 20, "Secondary schools": 14, 'Gym': 7,
         'Total population of the neighborhood' : 79737, 'Population Density': 18040.04, 'Hospitals': 3, 'Parks' : 2, 'Restaurants': 86, 
        'Cafes':21, 'Mosques': 47,	'Bus stations': 24, 'Metro stations':1,	'Supermarkets': 4,'Children_Ratio': 11.34, 'Youth_Ratio': 22.45, 
        'Adults_Ratio': 49.35, 'Seniors_Ratio': 16.83, 'Children': 9050, 'Youth': 17906, 'Males above 10 years': 43827 }

In [159]:
df = pd.concat([df, pd.DataFrame([zah])], ignore_index=True)

In [160]:
df['Park_ratio']= df['Parks'] / (df['Total population of the neighborhood']) * 2386

In [161]:
df['Hospitals_ratio']=  (df['Hospitals'] / df['Total population of the neighborhood']) * 10000

In [162]:
df['Gym_ratio']= df['Gym'] / df['Total population of the neighborhood'] * 5000

In [163]:
df['Rest_coffee_ratio'] = ((df['Restaurants'] + df['Cafes']) / df['Total population of the neighborhood']) * 1000

In [164]:
df['Elementary_schools_ratio'] = (df['Elementary schools'] / df['Children']) * 600

In [165]:
df['Secondary_schools_ratio'] = (df['Secondary schools'] / df['Youth']) * 600

In [166]:
df['Mosques_ratio'] = (df['Mosques'] / df['Males above 10 years']) * 1000

In [167]:
df

,Neighborhood,Elementary schools,Secondary schools,Gym,Total population of the neighborhood,Population Density,Hospitals,Parks,Restaurants,Cafes,...,Children,Youth,Males above 10 years,Park_ratio,Hospitals_ratio,Gym_ratio,Rest_coffee_ratio,Elementary_schools_ratio,Secondary_schools_ratio,Mosques_ratio
0,حي الفلاح,4,8,2,38710,9701.75,3,2,34,12,...,5797,8868,16295,0.123276,0.774994,0.258331,1.188323,0.414007,0.541272,1.288739
1,حي الياسمين,5,9,5,103116,8106.60,5,6,80,40,...,16955,21542,44016,0.138834,0.484891,0.242445,1.163738,0.176939,0.250673,1.363141
2,حي العزيزية,31,26,7,174869,8403.12,6,7,162,91,...,32055,41540,77024,0.095511,0.343114,0.20015,1.446797,0.580253,0.375542,1.376194
3,حي المنصورة,15,11,3,59401,10085.05,6,4,100,29,...,8789,14773,27247,0.160671,1.010084,0.252521,2.171681,1.024007,0.446761,1.835064
4,حي المونسية,5,8,11,86315,5623.12,3,4,121,46,...,17625,16565,34783,0.110572,0.347564,0.637201,1.934774,0.170213,0.289768,1.437484
5,حي الروضة,20,27,11,92956,10672.33,7,19,140,36,...,15883,17090,40609,0.487693,0.753044,0.591678,1.893369,0.755525,0.947923,1.255879
6,حي السويدي,19,19,11,115457,20992.18,8,8,93,60,...,12970,19146,67337,0.165326,0.692899,0.476368,1.325169,0.878951,0.595425,0.787086
7,حي الزهرة,20,14,7,79737,18040.04,3,2,86,21,...,9050,17906,43827,0.059847,0.376237,0.438943,1.341912,1.325967,0.469116,1.072398

In [168]:
df.columns

Index(['Neighborhood', 'Elementary schools', 'Secondary schools', 'Gym',
       'Total population of the neighborhood', 'Population Density',
       'Hospitals', 'Parks', 'Restaurants', 'Cafes', 'Mosques', 'Bus stations',
       'Metro stations', 'Supermarkets', 'Children_Ratio', 'Youth_Ratio',
       'Adults_Ratio', 'Seniors_Ratio', 'Children', 'Youth',
       'Males above 10 years', 'Park_ratio', 'Hospitals_ratio', 'Gym_ratio',
       'Rest_coffee_ratio', 'Elementary_schools_ratio',
       'Secondary_schools_ratio', 'Mosques_ratio'],
      dtype='object')

# High School

In [170]:
yas_schools = 9
falah_schools = 8
aziz_schools = 26
mansour_schools = 11  
roda_schools = 27 
monsia_schools = 6
swedi_schools = 19
zahr_schools = 14

### Density

In [172]:
yas_density = 103116 / 12.72
falah_density = 38710 / 3.99
aziz_density = 174869 / 20.81 
mansour_density = 59401 / 5.89 
roda_density = 92956 / 8.71 
monsa_density = 86315/15.35
swedi_density = 115457 / 5.5 
zahr_density = 79737 / 4.42

In [173]:
# def categorize_age(age):
#     if age == '0-9':
#         return 'Children'
#     elif age == '10-19':
#         return 'Youth'
#     elif age == '20-29':
#         return 'Adults'
#     elif age == '30-39':
#         return 'Adults'
#     elif age == '40-49':
#         return 'Adults'
#     elif age == '50-59':
#         return 'Seniors'
#     elif age == '60-69':
#         return 'Seniors'
#     elif age == '70-79':
#         return 'Seniors'
#     elif age == '80+':
#         return 'Seniors'
#     else:
#         return 'no' 

# # Apply the function to create a new column for age categories
# za['Age_Category'] = za['Age'].apply(categorize_age)

In [174]:
# za= za.sort_values(by=['Age','Gender'])

In [175]:
# total_population = za.iloc[-1]['Count']

# # Function to calculate ratio
# def calculate_ratio(category):
#     return (za.loc[rd['Age_Category'] == category, 'Count'].sum() / total_population) * 100

# # Add new columns
# za['Children_Ratio'] = calculate_ratio('Children')
# za['Youth_Ratio'] = calculate_ratio('Youth')
# za['Adults_Ratio'] = calculate_ratio('Adults')
# za['Seniors_Ratio'] = calculate_ratio('Seniors')

In [176]:
zahr_a = pd.read_csv('final_age_zahrah.csv')
swedi_a = pd.read_csv('final_age_swedi.csv')
yas_a = pd.read_csv('final_age_yasmin.csv')
falah_a = pd.read_csv('final_age_falah.csv')
aziz_a = pd.read_csv('final_age_azizya.csv')
mansour_a = pd.read_csv('final_age_mansora.csv')
roda_a = pd.read_csv('final_age_Rawdah.csv')
monsia_a = pd.read_csv('final_age_Munsiyah.csv')

In [177]:
# yas_pup = child = 16955 , youth = 21542  
# falah_pup = child = 5797 , youth = 8868 
# aziz_pup = child = 32055 , youth = 41540 
# mansour_pup = child = 8789 , youth = 14773  
# roda_pup = child = 15883 , youth = 17090
# monsia_pup = child = 17625 , youth = 16565 
# swedi_pup = child = 12970 , youth = 19146  
# zahr_pup = child = 9050 , youth = 17906

In [178]:
# yas_pray = 44016  
# falah_pray = 16295 
# aziz_pray = 77024 
# mansour_pray = 27247   
# roda_pray = 40609  
# monsia_pray = 34783  
# swedi_pray = 67337 
# zahr_pray = 43827

In [179]:
filtered_df = zahr_a[(zahr_a['Age'] != '0-9') & (yas_a['Gender'] == 'ذكور')]

# Calculate the sum of the 'Count' column
total_sum = filtered_df['Count'].sum()
total_sum

43827

In [180]:
#df.to_csv('ready1.csv', index=False)

In [181]:

benchmarks = {
    'Hospitals_ratio': 1.0,  
    'Elementary_schools_ratio': 1.0,  
    'Secondary_schools_ratio': 1.0,   
    'Gym_ratio': 1.0,           
    'Park_ratio': 1.0,          
    'Rest_coffee_ratio': 3.0,   
    'Mosques_ratio': 1.0              
}


unit_sizes = {
    'Hospitals_ratio': 10000,            
    'Elementary_schools_ratio': 800,     
    'Secondary_schools_ratio': 800,      
    'Gym_ratio': 5000,                   
    'Park_ratio': 2386,                  
    'Rest_coffee_ratio': 1000,           
    'Mosques_ratio': 1000                       
}


population_columns = {
    'Elementary_schools_ratio': 'Children',
    'Secondary_schools_ratio': 'Youth',
    'Hospitals_ratio': 'Total population of the neighborhood',
    'Gym_ratio': 'Total population of the neighborhood',
    'Park_ratio': 'Total population of the neighborhood',
    'Rest_coffee_ratio': 'Total population of the neighborhood',
    'Mosques_ratio': 'Males above 10 years'
}


def calculate_needed_units(row, factor, benchmark, unit_size, population_column):
    actual_ratio = row[factor]
    population = row[population_column]
    
    if actual_ratio < benchmark:
        
        additional_units = ((benchmark - actual_ratio) * population) / unit_size
        return max(int(additional_units), 0)  
    return 0  


for factor, benchmark in benchmarks.items():
    unit_size = unit_sizes[factor]
    population_column = population_columns[factor]
    column_name = factor.replace('_ratio', '_needed')  
    
    
    df[column_name] = df.apply(lambda row: calculate_needed_units(row, factor, benchmark, unit_size, population_column), axis=1)

In [182]:
df

,Neighborhood,Elementary schools,Secondary schools,Gym,Total population of the neighborhood,Population Density,Hospitals,Parks,Restaurants,Cafes,...,Elementary_schools_ratio,Secondary_schools_ratio,Mosques_ratio,Hospitals_needed,Elementary_schools_needed,Secondary_schools_needed,Gym_needed,Park_needed,Rest_coffee_needed,Mosques_needed
0,حي الفلاح,4,8,2,38710,9701.75,3,2,34,12,...,0.414007,0.541272,1.288739,0,4,5,5,14,70,0
1,حي الياسمين,5,9,5,103116,8106.60,5,6,80,40,...,0.176939,0.250673,1.363141,5,17,20,15,37,189,0
2,حي العزيزية,31,26,7,174869,8403.12,6,7,162,91,...,0.580253,0.375542,1.376194,11,16,32,27,66,271,0
3,حي المنصورة,15,11,3,59401,10085.05,6,4,100,29,...,1.024007,0.446761,1.835064,0,0,10,8,20,49,0
4,حي المونسية,5,8,11,86315,5623.12,3,4,121,46,...,0.170213,0.289768,1.437484,5,18,14,6,32,91,0
5,حي الروضة,20,27,11,92956,10672.33,7,19,140,36,...,0.755525,0.947923,1.255879,2,4,1,7,19,102,0
6,حي السويدي,19,19,11,115457,20992.18,8,8,93,60,...,0.878951,0.595425,0.787086,3,1,9,12,40,193,14
7,حي الزهرة,20,14,7,79737,18040.04,3,2,86,21,...,1.325967,0.469116,1.072398,4,0,11,8,31,132,0

In [183]:
#df.to_csv('ready1.csv', index=False)

In [184]:
weights = {
    'Elementary_schools_ratio': 0.2,
    'Secondary_schools_ratio': 0.2,
    'Hospitals_ratio': 0.2,
    'Gym_ratio': 0.1,
    'Park_ratio': 0.1,
    'Rest_coffee_ratio': 0.1,
    'Mosques_ratio': 0.1
}


def calculate_total_score_as_percentage(row, weights):
    total_score = 0
    for factor, weight in weights.items():
        
        if factor == 'Rest_coffee_ratio':
            normalized_ratio = row[factor] / 5 
            total_score += normalized_ratio * weight
        else:
            total_score += row[factor] * weight  
    return total_score * 100  


df['Total_Score_Percentage'] = df.apply(lambda row: calculate_total_score_as_percentage(row, weights), axis=1)

In [185]:
df

,Neighborhood,Elementary schools,Secondary schools,Gym,Total population of the neighborhood,Population Density,Hospitals,Parks,Restaurants,Cafes,...,Secondary_schools_ratio,Mosques_ratio,Hospitals_needed,Elementary_schools_needed,Secondary_schools_needed,Gym_needed,Park_needed,Rest_coffee_needed,Mosques_needed,Total_Score_Percentage
0,حي الفلاح,4,8,2,38710,9701.75,3,2,34,12,...,0.541272,1.288739,0,4,5,5,14,70,0,53.685559
1,حي الياسمين,5,9,5,103116,8106.60,5,6,80,40,...,0.250673,1.363141,5,17,20,15,37,189,0,38.021733
2,حي العزيزية,31,26,7,174869,8403.12,6,7,162,91,...,0.375542,1.376194,11,16,32,27,66,271,0,45.590319
3,حي المنصورة,15,11,3,59401,10085.05,6,4,100,29,...,0.446761,1.835064,0,0,10,8,20,49,0,76.442968
4,حي المونسية,5,8,11,86315,5623.12,3,4,121,46,...,0.289768,1.437484,5,18,14,6,32,91,0,41.873003
5,حي الروضة,20,27,11,92956,10672.33,7,19,140,36,...,0.947923,1.255879,2,4,1,7,19,102,0,76.269079
6,حي السويدي,19,19,11,115457,20992.18,8,8,93,60,...,0.595425,0.787086,3,1,9,12,40,193,14,60.283625
7,حي الزهرة,20,14,7,79737,18040.04,3,2,86,21,...,0.469116,1.072398,4,0,11,8,31,132,0,61.822108

In [186]:
df.columns

Index(['Neighborhood', 'Elementary schools', 'Secondary schools', 'Gym',
       'Total population of the neighborhood', 'Population Density',
       'Hospitals', 'Parks', 'Restaurants', 'Cafes', 'Mosques', 'Bus stations',
       'Metro stations', 'Supermarkets', 'Children_Ratio', 'Youth_Ratio',
       'Adults_Ratio', 'Seniors_Ratio', 'Children', 'Youth',
       'Males above 10 years', 'Park_ratio', 'Hospitals_ratio', 'Gym_ratio',
       'Rest_coffee_ratio', 'Elementary_schools_ratio',
       'Secondary_schools_ratio', 'Mosques_ratio', 'Hospitals_needed',
       'Elementary_schools_needed', 'Secondary_schools_needed', 'Gym_needed',
       'Park_needed', 'Rest_coffee_needed', 'Mosques_needed',
       'Total_Score_Percentage'],
      dtype='object')

In [187]:
start_year = 2024
end_year = 2030
years = list(range(start_year, end_year + 1))


build_rates = {
    'Mosques_needed': 4,  
    'Secondary_schools_needed': 1,  
    'Elementary_schools_needed': 1,  
    'Hospitals_needed': 1,  
    'Gym_needed': 2,  
    'Park_needed': 3,  
    'Rest_coffee_needed': 20  
}


build_periods = {
    'Mosques_needed': 1,  
    'Secondary_schools_needed': 2,  
    'Elementary_schools_needed': 1,  
    'Hospitals_needed': 3,  
    'Gym_needed': 1,  
    'Park_needed': 1,  
    'Rest_coffee_needed': 1  
}


def calculate_yearly_plan(instances_needed, build_rate_per_year, years, build_period=None):
    yearly_plan = {year: 0 for year in years} 
    remaining_instances = instances_needed     

    for year in years:
        
        if build_period:
            if (year - start_year) % build_period != 0:
                continue  

        if remaining_instances > 0:
            if remaining_instances >= build_rate_per_year:
                yearly_plan[year] = build_rate_per_year
                remaining_instances -= build_rate_per_year
            else:
                yearly_plan[year] = remaining_instances
                remaining_instances = 0  

    return yearly_plan


def flatten_plan(df, factor_column, build_rate, build_period):
    flat_data = []
    for _, row in df.iterrows():
        neighborhood = row['Neighborhood']
        instances_needed = row[factor_column]
        plan = calculate_yearly_plan(instances_needed, build_rate, years, build_period)
        for year, count in plan.items():
            
            if count > 0:
                flat_data.append({'Neighborhood': neighborhood, 'Year': year, 'Factor': factor_column, 'Instances_Built': count})
    return pd.DataFrame(flat_data)


mosques_flat = flatten_plan(df, 'Mosques_needed', build_rates['Mosques_needed'], build_periods['Mosques_needed'])
secondary_schools_flat = flatten_plan(df, 'Secondary_schools_needed', build_rates['Secondary_schools_needed'], build_periods['Secondary_schools_needed'])
elementary_schools_flat = flatten_plan(df, 'Elementary_schools_needed', build_rates['Elementary_schools_needed'], build_periods['Elementary_schools_needed'])
hospitals_flat = flatten_plan(df, 'Hospitals_needed', build_rates['Hospitals_needed'], build_periods['Hospitals_needed'])
gyms_flat = flatten_plan(df, 'Gym_needed', build_rates['Gym_needed'], build_periods['Gym_needed'])
parks_flat = flatten_plan(df, 'Park_needed', build_rates['Park_needed'], build_periods['Park_needed'])
rest_coffee_flat = flatten_plan(df, 'Rest_coffee_needed', build_rates['Rest_coffee_needed'], build_periods['Rest_coffee_needed'])


final_df = pd.concat([mosques_flat, secondary_schools_flat, elementary_schools_flat, hospitals_flat, gyms_flat, parks_flat, rest_coffee_flat])

In [188]:
final_df[final_df['Factor'] == 'Hospitals_needed']

   Neighborhood  Year            Factor  Instances_Built
0   حي الياسمين  2024  Hospitals_needed                1
1   حي الياسمين  2027  Hospitals_needed                1
2   حي الياسمين  2030  Hospitals_needed                1
3   حي العزيزية  2024  Hospitals_needed                1
4   حي العزيزية  2027  Hospitals_needed                1
5   حي العزيزية  2030  Hospitals_needed                1
6   حي المونسية  2024  Hospitals_needed                1
7   حي المونسية  2027  Hospitals_needed                1
8   حي المونسية  2030  Hospitals_needed                1
9     حي الروضة  2024  Hospitals_needed                1
10    حي الروضة  2027  Hospitals_needed                1
11   حي السويدي  2024  Hospitals_needed                1
12   حي السويدي  2027  Hospitals_needed                1
13   حي السويدي  2030  Hospitals_needed                1
14    حي الزهرة  2024  Hospitals_needed                1
15    حي الزهرة  2027  Hospitals_needed                1
16    حي الزهرة  2030  Hospitals_needed                1

In [189]:
final_df

   Neighborhood  Year                    Factor  Instances_Built
0    حي السويدي  2024            Mosques_needed                4
1    حي السويدي  2025            Mosques_needed                4
2    حي السويدي  2026            Mosques_needed                4
3    حي السويدي  2027            Mosques_needed                2
0     حي الفلاح  2024  Secondary_schools_needed                1
..          ...   ...                       ...              ...
41    حي الزهرة  2026        Rest_coffee_needed               20
42    حي الزهرة  2027        Rest_coffee_needed               20
43    حي الزهرة  2028        Rest_coffee_needed               20
44    حي الزهرة  2029        Rest_coffee_needed               20
45    حي الزهرة  2030        Rest_coffee_needed               12

[218 rows x 4 columns]

In [190]:
#df.to_csv('ready.csv', index=False)

In [191]:
#final_df.to_csv('for_Trendcharts.csv', index=False)